# Generated by Django 3.2.5 on 2021-08-08 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='_')),
                ('income_date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('SALARY', 'SALARY'), ('BUSINESS', 'BUSINESS'), ('SIDE_HUSLES', 'SIDE_HUSLES'), ('OTHERS', 'OTHERS')], max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(default='SALARY', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserIncome',
        ),
    ]
